env:
  browser: true
  commonjs: true
  es2021: true
ignorePatterns:
  - '*.svelte'
  - '**/dist'
extends:
  - 'eslint:recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
plugins:
  - 'prettier'
  - '@typescript-eslint'
rules:
  accessor-pairs: error
  array-bracket-newline: 'off'
  array-bracket-spacing:
    - error
    - never
  array-callback-return: error
  array-element-newline: 'off'
  arrow-body-style: 'off'
  arrow-parens:
    - error
    - always
  arrow-spacing:
    - error
    - after: true
      before: true
  block-scoped-var: 'off'
  block-spacing:
    - error
    - always
  brace-style: 'off'
  camelcase: error
  capitalized-comments: 'off'
  class-methods-use-this: 'off'
  comma-dangle: 'off'
  comma-spacing:
    - error
    - after: true
      before: false
  comma-style:
    - error
    - last
  complexity: 'off'
  computed-property-spacing:
    - error
    - never
  consistent-return: 'off'
  consistent-this: error
  curly: 'off'
  default-case: error
  default-case-last: error
  default-param-last: 'off'
  dot-location:
    - error
    - property
  dot-notation:
    - error
    - allowKeywords: true
  eol-last: 'off'
  eqeqeq: 'off'
  func-call-spacing: error
  func-name-matching: error
  func-names: 'off'
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
  function-call-argument-newline:
    - error
    - consistent
  function-paren-newline: 'off'
  generator-star-spacing: error
  grouped-accessor-pairs: error
  guard-for-in: 'off'
  id-denylist: error
  id-length: 'off'
  id-match: error
  implicit-arrow-linebreak: 'off'
  indent: 'off' #['error', 2]
  init-declarations: 'off'
  jsx-quotes: error
  key-spacing: error
  keyword-spacing:
    - error
    - after: true
      before: true
  line-comment-position: 'off'
  linebreak-style:
    - error
    - unix
  lines-around-comment: 'off'
  lines-between-class-members:
    - error
    - always
    - exceptAfterSingleLine: true
  max-classes-per-file: error
  max-depth:
    - error
    - max: 6
  max-len: 'off'
  max-lines: 'off'
  max-lines-per-function: 'off'
  max-nested-callbacks: error
  max-params: 'off'
  max-statements: 'off'
  max-statements-per-line: 'off'
  multiline-comment-style:
    'off'
    # - error
    # - separate-lines
  multiline-ternary:
    - error
    - always-multiline
  new-parens: error
  newline-per-chained-call: 'off'
  no-alert: error
  no-array-constructor: error
  no-async-promise-executor: 'off'
  no-await-in-loop: 'off'
  no-bitwise: error
  no-caller: error
  no-confusing-arrow: 'off'
  no-console: 'off'
  no-constant-condition: 'off'
  no-constructor-return: error
  no-continue: 'off'
  no-debugger: 'off'
  no-div-regex: error
  no-duplicate-imports: error
  no-else-return:
    - error
    - allowElseIf: true
  no-empty:
    - error
    - allowEmptyCatch: true
  no-empty-function: 'off'
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-extra-parens: 'off'
  no-extra-semi: 'off'
  no-floating-decimal: error
  no-implicit-coercion: error
  no-implicit-globals: 'off'
  no-implied-eval: error
  no-inline-comments: 'off'
  no-inner-declarations:
    - error
    - functions
  no-invalid-this: error
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: 'off'
  no-loop-func: 'off'
  no-loss-of-precision: error
  no-magic-numbers: 'off'
  no-mixed-operators: 'off'
  no-multi-assign: error
  no-multi-spaces: error
  no-multi-str: error
  no-multiple-empty-lines: error
  no-negated-condition: 'off'
  no-nested-ternary: 'off'
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-wrappers: error
  no-nonoctal-decimal-escape: error
  no-octal-escape: error
  no-param-reassign: 'off'
  no-plusplus: 'off'
  no-promise-executor-return: error
  no-proto: error
  no-restricted-exports: error
  no-restricted-globals: error
  no-restricted-imports: error
  no-restricted-properties: error
  no-restricted-syntax: error
  no-return-assign: error
  no-return-await: 'off'
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-shadow: 'off'
  no-tabs:
    - error
    - allowIndentationTabs: true
  no-template-curly-in-string: error
  no-ternary: 'off'
  no-throw-literal: error
  no-trailing-spaces:
    - warn
    - skipBlankLines: true
      ignoreComments: true
  no-undef-init: error
  no-undef: 'off'
  no-undefined: 'off'
  no-underscore-dangle: 'off'
  no-unmodified-loop-condition: 'off'
  no-unneeded-ternary: error
  no-unreachable-loop: error
  no-unsafe-optional-chaining: error
  no-unused-expressions: error
  no-unused-vars: 'off'
  no-use-before-define: 'off'
  no-useless-backreference: error
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-rename: error
  no-useless-return: error
  no-var: error
  no-void: error
  no-warning-comments: 'off'
  no-whitespace-before-property: error
  nonblock-statement-body-position: 'off'
  object-curly-newline: 'off'
  object-curly-spacing:
    - error
    - always
  object-shorthand: 'off'
  one-var: 'off'
  one-var-declaration-per-line:
    - error
    - initializations
  operator-assignment:
    - error
    - always
  operator-linebreak:
    - error
    - null
  padded-blocks: 'off'
  padding-line-between-statements: error
  prefer-arrow-callback: error
  prefer-const: 'off'
  prefer-destructuring: 'off'
  prefer-exponentiation-operator: error
  prefer-named-capture-group: 'off'
  prefer-numeric-literals: error
  prefer-object-spread: error
  prefer-promise-reject-errors: error
  prefer-regex-literals: error
  prefer-rest-params: 'off'
  prefer-spread: error
  prefer-template: 'off'
  quote-props: 'off'
  quotes:
    - error
    - backtick
  radix:
    - error
    - as-needed
  require-atomic-updates: 'off'
  require-await: 'off'
  require-unicode-regexp: 'off'
  rest-spread-spacing:
    - error
    - never
  semi:
    - error
    - never
  semi-spacing:
    - error
    - after: true
      before: false
  semi-style: 'off'
  sort-imports: 'off'
  sort-keys: 'off'
  sort-vars: 'off'
  space-before-blocks: error
  space-before-function-paren: 'off'
  space-in-parens:
    - error
    - never
  space-infix-ops: error
  space-unary-ops:
    - error
    - nonwords: false
      words: true
  spaced-comment:
    - error
    - always
  strict:
    - error
    - never
  switch-colon-spacing: error
  symbol-description: error
  template-curly-spacing:
    - error
    - never
  template-tag-spacing: error
  unicode-bom:
    - error
    - never
  vars-on-top: 'off'
  wrap-iife: error
  wrap-regex: 'off'
  yield-star-spacing: error
  yoda:
    - error
    - never
